version: "2"

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - unconvert

formatters:
  settings:
    gofmt:
      simplify: true

linters-settings:
  govet:
    shadow: true

issues:
  exclude-rules:
    - path: ".*_test\\.go$"
      linters:
        - staticcheck
        - unconvert
    - path: benchmarks/
      linters:
        - staticcheck
        - unconvert
    - path: plugins/
      linters:
        - staticcheck
        - unconvert
