# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - id: filo
    binary: filo
    main: ./cmd/filo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/supunhg/filo-go/internal/cli.version={{.Version}}

archives:
  - id: filo
    builds:
      - filo
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: supunhg
    name: filo-go
  draft: false
  prerelease: auto
