package export

import (
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"strings"
)

// HTMLReport represents an HTML report
type HTMLReport struct {
	Title       string
	Description string
	GeneratedAt string
	ToolVersion string
	Sections    []ReportSection
}

// ReportSection represents a section in the report
type ReportSection struct {
	Title   string
	Content string
	Type    string // "text", "table", "list", "code"
}

// GenerateHTMLReport generates an HTML report from analysis results
func GenerateHTMLReport(results *AnalysisResults, outputPath string) error {
	report := &HTMLReport{
		Title:       "Filo Analysis Report",
		Description: "Forensic analysis report generated by filo-go",
		GeneratedAt: results.Timestamp,
		ToolVersion: "0.2.0",
		Sections:    []ReportSection{},
	}

	// Add file info section
	if results.FileInfo != nil {
		report.Sections = append(report.Sections, ReportSection{
			Title: "File Information",
			Content: fmt.Sprintf(`<table class="data-table">
				<tr><th>Name</th><td>%s</td></tr>
				<tr><th>Size</th><td>%d bytes</td></tr>
				<tr><th>Type</th><td>%s</td></tr>
				<tr><th>MIME</th><td>%s</td></tr>
				<tr><th>SHA256</th><td><code>%s</code></td></tr>
				<tr><th>Entropy</th><td>%.2f</td></tr>
			</table>`,
				results.FileInfo.Name,
				results.FileInfo.Size,
				results.FileInfo.Type,
				results.FileInfo.MIME,
				results.FileInfo.SHA256,
				results.FileInfo.Entropy),
			Type: "table",
		})
	}

	// Add signatures section
	if len(results.Signatures) > 0 {
		var sigList []string
		for _, sig := range results.Signatures {
			sigList = append(sigList, fmt.Sprintf("<li><strong>%s</strong> - %s (offset: %d, confidence: %.1f%%)</li>",
				sig.Name, sig.Description, sig.Offset, sig.Confidence*100))
		}
		report.Sections = append(report.Sections, ReportSection{
			Title:   "Detected Signatures",
			Content: fmt.Sprintf("<ul>%s</ul>", strings.Join(sigList, "")),
			Type:    "list",
		})
	}

	// Add strings section
	if len(results.Strings) > 0 {
		var stringList []string
		for i, s := range results.Strings {
			if i >= 100 { // Limit to 100 strings
				break
			}
			stringList = append(stringList, fmt.Sprintf("<tr><td>0x%X</td><td>%s</td><td>%s</td></tr>",
				s.Offset, s.Type, template.HTMLEscapeString(s.Value)))
		}
		report.Sections = append(report.Sections, ReportSection{
			Title: "Extracted Strings",
			Content: fmt.Sprintf(`<table class="data-table">
				<tr><th>Offset</th><th>Type</th><th>Value</th></tr>
				%s
			</table>`, strings.Join(stringList, "")),
			Type: "table",
		})
	}

	// Add metadata section
	if len(results.Metadata) > 0 {
		var metaList []string
		for key, value := range results.Metadata {
			metaList = append(metaList, fmt.Sprintf("<tr><td>%s</td><td>%s</td></tr>",
				template.HTMLEscapeString(key), template.HTMLEscapeString(fmt.Sprintf("%v", value))))
		}
		report.Sections = append(report.Sections, ReportSection{
			Title: "Metadata",
			Content: fmt.Sprintf(`<table class="data-table">
				<tr><th>Key</th><th>Value</th></tr>
				%s
			</table>`, strings.Join(metaList, "")),
			Type: "table",
		})
	}

	// Add security section
	if len(results.SecurityIssues) > 0 {
		var securityList []string
		for _, issue := range results.SecurityIssues {
			severityClass := "info"
			switch issue.Severity {
			case "high":
				severityClass = "danger"
			case "medium":
				severityClass = "warning"
			}
			securityList = append(securityList, fmt.Sprintf(`<tr>
				<td><span class="badge badge-%s">%s</span></td>
				<td>%s</td>
				<td>%s</td>
			</tr>`,
				severityClass,
				issue.Severity,
				template.HTMLEscapeString(issue.Type),
				template.HTMLEscapeString(issue.Description)))
		}
		report.Sections = append(report.Sections, ReportSection{
			Title: "Security Issues",
			Content: fmt.Sprintf(`<table class="data-table">
				<tr><th>Severity</th><th>Type</th><th>Description</th></tr>
				%s
			</table>`, strings.Join(securityList, "")),
			Type: "table",
		})
	}

	// Generate HTML
	html := generateHTML(report)

	// Write to file
	if err := os.WriteFile(outputPath, []byte(html), 0644); err != nil {
		return err
	}

	return nil
}

// generateHTML generates the HTML content
func generateHTML(report *HTMLReport) string {
	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>%s</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        header {
            background: linear-gradient(135deg, #667eea 0%%, #764ba2 100%%);
            color: white;
            padding: 40px 20px;
            text-align: center;
            margin-bottom: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }
        .meta {
            opacity: 0.9;
            font-size: 0.9em;
        }
        .section {
            background: white;
            border-radius: 10px;
            padding: 25px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }
        h2 {
            color: #667eea;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #eee;
        }
        .data-table {
            width: 100%%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        .data-table th,
        .data-table td {
            padding: 12px 15px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }
        .data-table th {
            background: #f8f9fa;
            font-weight: 600;
            color: #555;
        }
        .data-table tr:hover {
            background: #f8f9fa;
        }
        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.85em;
            font-weight: 600;
        }
        .badge-danger {
            background: #dc3545;
            color: white;
        }
        .badge-warning {
            background: #ffc107;
            color: #333;
        }
        .badge-info {
            background: #17a2b8;
            color: white;
        }
        code {
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
            font-size: 0.9em;
            word-break: break-all;
        }
        ul {
            list-style: none;
            padding-left: 0;
        }
        ul li {
            padding: 10px 0;
            border-bottom: 1px solid #eee;
        }
        footer {
            text-align: center;
            padding: 20px;
            color: #666;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>%s</h1>
            <p class="meta">%s</p>
            <p class="meta">Generated: %s</p>
        </header>
        
        <main>
%s
        </main>
        
        <footer>
            <p>Generated by <strong>filo-go</strong> v%s</p>
            <p>Forensic Intelligence & Learning Operator</p>
        </footer>
    </div>
</body>
</html>`,
		report.Title,
		report.Title,
		report.Description,
		report.GeneratedAt,
		generateSections(report.Sections),
		report.ToolVersion)
}

// generateSections generates HTML for all sections
func generateSections(sections []ReportSection) string {
	var html strings.Builder
	for _, section := range sections {
		html.WriteString(fmt.Sprintf(`        <div class="section">
            <h2>%s</h2>
            %s
        </div>
`, section.Title, section.Content))
	}
	return html.String()
}

// AnalysisResults represents the analysis results for HTML export
type AnalysisResults struct {
	Timestamp      string
	FileInfo       *FileInfo
	Signatures     []SignatureMatch
	Strings        []ExtractedString
	Metadata       map[string]interface{}
	SecurityIssues []SecurityIssue
}

// FileInfo represents file information
type FileInfo struct {
	Name    string
	Size    int64
	Type    string
	MIME    string
	SHA256  string
	Entropy float64
}

// SignatureMatch represents a signature match
type SignatureMatch struct {
	Name        string
	Description string
	Offset      int64
	Confidence  float64
}

// ExtractedString represents an extracted string
type ExtractedString struct {
	Offset int64
	Type   string
	Value  string
}

// SecurityIssue represents a security issue
type SecurityIssue struct {
	Severity    string
	Type        string
	Description string
}

// FormatHTMLPath formats a path for HTML output
func FormatHTMLPath(inputPath string) string {
	dir := filepath.Dir(inputPath)
	name := filepath.Base(inputPath)
	ext := filepath.Ext(name)
	base := strings.TrimSuffix(name, ext)

	return filepath.Join(dir, base+".html")
}
