package export

import (
	"encoding/json"
	"fmt"
	"html/template"
	"os"
	"strings"
	"time"
)

// InteractiveReport represents a full interactive HTML report
type InteractiveReport struct {
	Title       string               `json:"title"`
	Description string               `json:"description"`
	GeneratedAt string               `json:"generated_at"`
	ToolVersion string               `json:"tool_version"`
	FileInfo    *FileInfo            `json:"file_info,omitempty"`
	Summary     *ReportSummary       `json:"summary,omitempty"`
	Sections    []InteractiveSection `json:"sections"`
}

// ReportSummary contains dashboard metrics
type ReportSummary struct {
	TotalSignatures int     `json:"total_signatures"`
	TotalStrings    int     `json:"total_strings"`
	TotalIssues     int     `json:"total_issues"`
	Entropy         float64 `json:"entropy"`
	RiskScore       float64 `json:"risk_score"`
	RiskLevel       string  `json:"risk_level"`
	Format          string  `json:"format"`
	Confidence      float64 `json:"confidence"`
}

// InteractiveSection represents a collapsible section with filtering
type InteractiveSection struct {
	ID          string        `json:"id"`
	Title       string        `json:"title"`
	Type        string        `json:"type"`
	Filterable  bool          `json:"filterable"`
	Columns     []ColumnDef   `json:"columns,omitempty"`
	Rows        []interface{} `json:"rows,omitempty"`
	EntropyData []EntropyBar  `json:"entropy_data,omitempty"`
}

// ColumnDef defines a table column
type ColumnDef struct {
	Key   string `json:"key"`
	Label string `json:"label"`
	Width string `json:"width,omitempty"`
	Align string `json:"align,omitempty"`
}

// EntropyBar represents an entropy visualization bar
type EntropyBar struct {
	Offset  int64   `json:"offset"`
	Entropy float64 `json:"entropy"`
}

// GenerateInteractiveReport generates a self-contained interactive HTML report
func GenerateInteractiveReport(results *AnalysisResults, outputPath string) error {
	report := buildInteractiveReport(results)
	html, err := renderInteractiveHTML(report)
	if err != nil {
		return fmt.Errorf("failed to render HTML: %w", err)
	}
	return os.WriteFile(outputPath, []byte(html), 0644)
}

func buildInteractiveReport(results *AnalysisResults) *InteractiveReport {
	report := &InteractiveReport{
		Title:       "Filo Forensic Analysis Report",
		Description: "Interactive forensic analysis report generated by filo-go",
		GeneratedAt: time.Now().Format(time.RFC3339),
		ToolVersion: "0.4.0",
		FileInfo:    results.FileInfo,
		Summary:     buildSummary(results),
		Sections:    []InteractiveSection{},
	}

	if results.FileInfo != nil {
		report.Sections = append(report.Sections, InteractiveSection{
			ID:    "file-info",
			Title: "File Information",
			Type:  "info",
		})
	}

	if len(results.Signatures) > 0 {
		rows := make([]interface{}, len(results.Signatures))
		for i, sig := range results.Signatures {
			rows[i] = map[string]interface{}{
				"name":        sig.Name,
				"description": sig.Description,
				"offset":      fmt.Sprintf("0x%X", sig.Offset),
				"confidence":  fmt.Sprintf("%.1f%%", sig.Confidence*100),
			}
		}
		report.Sections = append(report.Sections, InteractiveSection{
			ID:         "signatures",
			Title:      fmt.Sprintf("Detected Signatures (%d)", len(results.Signatures)),
			Type:       "table",
			Filterable: true,
			Columns: []ColumnDef{
				{Key: "name", Label: "Name", Width: "20%"},
				{Key: "description", Label: "Description", Width: "40%"},
				{Key: "offset", Label: "Offset", Width: "20%", Align: "right"},
				{Key: "confidence", Label: "Confidence", Width: "20%", Align: "right"},
			},
			Rows: rows,
		})
	}

	if len(results.Strings) > 0 {
		rows := make([]interface{}, 0)
		for i, s := range results.Strings {
			if i >= 500 {
				break
			}
			rows = append(rows, map[string]interface{}{
				"offset": fmt.Sprintf("0x%X", s.Offset),
				"type":   s.Type,
				"value":  s.Value,
			})
		}
		report.Sections = append(report.Sections, InteractiveSection{
			ID:         "strings",
			Title:      fmt.Sprintf("Extracted Strings (%d)", len(results.Strings)),
			Type:       "table",
			Filterable: true,
			Columns: []ColumnDef{
				{Key: "offset", Label: "Offset", Width: "15%", Align: "right"},
				{Key: "type", Label: "Type", Width: "15%"},
				{Key: "value", Label: "Value", Width: "70%"},
			},
			Rows: rows,
		})
	}

	if len(results.Metadata) > 0 {
		rows := make([]interface{}, 0)
		for k, v := range results.Metadata {
			rows = append(rows, map[string]interface{}{
				"key":   k,
				"value": fmt.Sprintf("%v", v),
			})
		}
		report.Sections = append(report.Sections, InteractiveSection{
			ID:         "metadata",
			Title:      fmt.Sprintf("Metadata (%d)", len(results.Metadata)),
			Type:       "table",
			Filterable: true,
			Columns: []ColumnDef{
				{Key: "key", Label: "Key", Width: "30%"},
				{Key: "value", Label: "Value", Width: "70%"},
			},
			Rows: rows,
		})
	}

	if len(results.SecurityIssues) > 0 {
		rows := make([]interface{}, len(results.SecurityIssues))
		for i, issue := range results.SecurityIssues {
			rows[i] = map[string]interface{}{
				"severity":    issue.Severity,
				"type":        issue.Type,
				"description": issue.Description,
			}
		}
		report.Sections = append(report.Sections, InteractiveSection{
			ID:         "security",
			Title:      fmt.Sprintf("Security Issues (%d)", len(results.SecurityIssues)),
			Type:       "table",
			Filterable: true,
			Columns: []ColumnDef{
				{Key: "severity", Label: "Severity", Width: "15%"},
				{Key: "type", Label: "Type", Width: "25%"},
				{Key: "description", Label: "Description", Width: "60%"},
			},
			Rows: rows,
		})
	}

	if results.FileInfo != nil && results.FileInfo.Entropy > 0 {
		report.Sections = append(report.Sections, InteractiveSection{
			ID:    "entropy",
			Title: "Entropy Analysis",
			Type:  "entropy",
			EntropyData: []EntropyBar{
				{Offset: 0, Entropy: results.FileInfo.Entropy},
			},
		})
	}

	return report
}

func buildSummary(results *AnalysisResults) *ReportSummary {
	summary := &ReportSummary{
		TotalSignatures: len(results.Signatures),
		TotalStrings:    len(results.Strings),
		TotalIssues:     len(results.SecurityIssues),
	}

	if results.FileInfo != nil {
		summary.Entropy = results.FileInfo.Entropy
		summary.Format = results.FileInfo.Type
	}

	riskScore := 0.0
	if results.FileInfo != nil && results.FileInfo.Entropy > 7.0 {
		riskScore += 0.3
	}
	riskScore += float64(len(results.SecurityIssues)) * 0.2
	if riskScore > 1.0 {
		riskScore = 1.0
	}
	summary.RiskScore = riskScore

	switch {
	case riskScore >= 0.8:
		summary.RiskLevel = "critical"
	case riskScore >= 0.6:
		summary.RiskLevel = "high"
	case riskScore >= 0.4:
		summary.RiskLevel = "medium"
	case riskScore >= 0.2:
		summary.RiskLevel = "low"
	default:
		summary.RiskLevel = "info"
	}

	return summary
}

func renderInteractiveHTML(report *InteractiveReport) (string, error) {
	reportJSON, err := json.Marshal(report)
	if err != nil {
		return "", err
	}

	tmpl := `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{.Title}}</title>
<style>
:root{--primary:#667eea;--danger:#dc3545;--warning:#ffc107;--success:#28a745;--info:#17a2b8;--bg:#f0f2f5;--card:#fff;--text:#333;--text-muted:#666;--border:#e0e0e0;--radius:12px;--shadow:0 2px 8px rgba(0,0,0,0.08)}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:var(--bg);color:var(--text);line-height:1.6}
.container{max-width:1400px;margin:0 auto;padding:20px}
header{background:linear-gradient(135deg,var(--primary) 0%,#764ba2 100%);color:white;padding:40px 30px;border-radius:var(--radius);margin-bottom:24px;box-shadow:var(--shadow)}
header h1{font-size:2em;margin-bottom:8px}
header .meta{opacity:0.9;font-size:0.9em}
.dashboard{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px;margin-bottom:24px}
.metric-card{background:var(--card);border-radius:var(--radius);padding:20px;box-shadow:var(--shadow);text-align:center}
.metric-card .value{font-size:1.8em;font-weight:700;color:var(--primary)}
.metric-card .label{font-size:0.85em;color:var(--text-muted);margin-top:4px}
.risk-critical .value{color:var(--danger)}
.risk-high .value{color:#e67e22}
.risk-medium .value{color:var(--warning)}
.risk-low .value{color:var(--success)}
.risk-info .value{color:var(--info)}
.section{background:var(--card);border-radius:var(--radius);margin-bottom:16px;box-shadow:var(--shadow);overflow:hidden}
.section-header{display:flex;justify-content:space-between;align-items:center;padding:16px 20px;cursor:pointer;user-select:none}
.section-header:hover{background:#f8f9fa}
.section-header h2{font-size:1.1em;color:var(--primary)}
.section-header .toggle{font-size:1.2em;color:var(--text-muted);transition:transform 0.3s}
.section-header .toggle.collapsed{transform:rotate(-90deg)}
.section-content{padding:0 20px 20px;overflow:hidden;transition:max-height 0.3s ease}
.section-content.collapsed{max-height:0;padding:0 20px}
.filter-bar{margin-bottom:12px}
.filter-bar input{width:100%;padding:8px 12px;border:1px solid var(--border);border-radius:6px;font-size:0.9em;outline:none}
.filter-bar input:focus{border-color:var(--primary)}
table{width:100%;border-collapse:collapse}
th,td{padding:10px 12px;text-align:left;border-bottom:1px solid var(--border);font-size:0.9em}
th{background:#f8f9fa;font-weight:600;color:var(--text-muted);position:sticky;top:0}
tr:hover{background:#f8f9fa}
.badge{display:inline-block;padding:3px 8px;border-radius:4px;font-size:0.8em;font-weight:600}
.badge-critical{background:var(--danger);color:white}
.badge-high{background:#e67e22;color:white}
.badge-medium{background:var(--warning);color:#333}
.badge-low{background:var(--success);color:white}
.badge-info{background:var(--info);color:white}
.entropy-bar{display:flex;align-items:flex-end;height:200px;gap:2px;padding:10px 0}
.entropy-segment{flex:1;border-radius:3px 3px 0 0;min-width:4px;position:relative}
.entropy-segment:hover{opacity:0.8}
.entropy-segment .tooltip{display:none;position:absolute;bottom:100%;left:50%;transform:translateX(-50%);background:#333;color:white;padding:4px 8px;border-radius:4px;font-size:0.75em;white-space:nowrap;z-index:10}
.entropy-segment:hover .tooltip{display:block}
.info-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px}
.info-item{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--border)}
.info-item .key{color:var(--text-muted);font-size:0.9em}
.info-item .val{font-weight:500;font-size:0.9em;word-break:break-all}
code{background:#f4f4f4;padding:2px 6px;border-radius:3px;font-family:'Monaco','Menlo',monospace;font-size:0.85em}
footer{text-align:center;padding:20px;color:var(--text-muted);font-size:0.85em}
</style>
</head>
<body>
<div class="container">
<header>
<h1>{{.Title}}</h1>
<p class="meta">{{.Description}}</p>
<p class="meta">Generated: {{.GeneratedAt}} | Version: {{.ToolVersion}}</p>
</header>
<div id="dashboard" class="dashboard"></div>
<div id="sections"></div>
<footer><p>Generated by <strong>filo-go</strong> v{{.ToolVersion}}</p><p>Forensic Intelligence &amp; Learning Operator</p></footer>
</div>
<script>
var REPORT={{.JSON}};

function init(){
renderDashboard();
renderSections();
}

function renderDashboard(){
var d=document.getElementById("dashboard");
var s=REPORT.summary||{};
var cards=[
{value:REPORT.file_info?formatSize(REPORT.file_info.size):"N/A",label:"File Size"},
{value:s.format||"Unknown",label:"Format"},
{value:s.entropy?s.entropy.toFixed(2):"N/A",label:"Entropy"},
{value:s.total_signatures||0,label:"Signatures"},
{value:s.total_strings||0,label:"Strings"},
{value:s.total_issues||0,label:"Issues"},
{value:s.risk_level||"info",label:"Risk Level",cls:"risk-"+(s.risk_level||"info")},
{value:s.confidence?(s.confidence*100).toFixed(0)+"%":"N/A",label:"Confidence"}
];
var html="";
for(var i=0;i<cards.length;i++){
var c=cards[i];
html+='<div class="metric-card '+(c.cls||'')+'"><div class="value">'+c.value+'</div><div class="label">'+c.label+'</div></div>';
}
d.innerHTML=html;
}

function renderSections(){
var container=document.getElementById("sections");
var html="";
for(var i=0;i<REPORT.sections.length;i++){
html+=renderSection(REPORT.sections[i]);
}
container.innerHTML=html;
for(var i=0;i<REPORT.sections.length;i++){
var s=REPORT.sections[i];
if(s.filterable)setupFilter(s.id);
if(s.type==="entropy")renderEntropyChart(s.id,s.entropy_data);
}
}

function renderSection(s){
var content=s.type==="info"?renderInfoSection(s):renderTableSection(s);
var filter=s.filterable?'<div class="filter-bar"><input type="text" id="filter-'+s.id+'" placeholder="Filter..." oninput="filterTable(\''+s.id+'\')"></div>':'';
return '<div class="section" id="section-'+s.id+'">'+
'<div class="section-header" onclick="toggleSection(\''+s.id+'\')">'+
'<h2>'+escHtml(s.title)+'</h2>'+
'<span class="toggle" id="toggle-'+s.id+'">&#9660;</span>'+
'</div>'+
'<div class="section-content" id="content-'+s.id+'">'+
filter+content+
'</div></div>';
}

function renderInfoSection(s){
if(!REPORT.file_info)return "<p>No file information available</p>";
var f=REPORT.file_info;
var items=[["Name",f.name],["Size",formatSize(f.size)],["Type",f.type],["MIME",f.mime],["SHA256","<code>"+escHtml(f.sha256)+"</code>"],["Entropy",f.entropy?f.entropy.toFixed(2):"N/A"]];
var html='<div class="info-grid">';
for(var i=0;i<items.length;i++){
html+='<div class="info-item"><span class="key">'+items[i][0]+'</span><span class="val">'+items[i][1]+'</span></div>';
}
return html+"</div>";
}

function renderTableSection(s){
if(!s.rows||s.rows.length===0)return "<p>No data available</p>";
var cols=s.columns;
if(!cols){
cols=[];
var keys=Object.keys(s.rows[0]);
for(var i=0;i<keys.length;i++){
cols.push({key:keys[i],label:keys[i]});
}
}
var header="<thead><tr>";
for(var i=0;i<cols.length;i++){
var c=cols[i];
header+='<th style="width:'+(c.width||"auto")+';text-align:'+(c.align||"left")+'">'+escHtml(c.label)+"</th>";
}
header+="</tr></thead>";
var body="<tbody>";
for(var i=0;i<s.rows.length;i++){
var r=s.rows[i];
var rowClass=r.severity?' class="severity-'+r.severity+'"':"";
body+="<tr"+rowClass+">";
for(var j=0;j<cols.length;j++){
var c=cols[j];
var val=r[c.key]||"";
if(c.key==="severity"){
val='<span class="badge badge-'+val+'">'+escHtml(val)+"</span>";
} else if(c.key==="confidence"||c.key==="Confidence"){
var num=parseFloat(val);
var color=num>=80?"var(--success)":num>=50?"var(--warning)":"var(--danger)";
val='<span style="color:'+color+';font-weight:600">'+escHtml(val)+"</span>";
} else {
val=escHtml(String(val));
}
body+='<td style="text-align:'+(c.align||"left")+'">'+val+"</td>";
}
body+="</tr>";
}
body+="</tbody>";
return '<div style="overflow-x:auto"><table id="table-'+s.id+'">'+header+body+"</table></div>";
}

function renderEntropyChart(id,data){
if(!data||data.length===0)return;
var container=document.getElementById("content-"+id);
if(!container)return;
var maxE=8;
var html='<div class="entropy-bar">';
for(var i=0;i<data.length;i++){
var d=data[i];
var h=Math.max(5,(d.entropy/maxE)*100);
var color=d.entropy<2?"var(--success)":d.entropy<4?"#4facfe":d.entropy<6?"var(--warning)":d.entropy<7?"#e67e22":"var(--danger)";
html+='<div class="entropy-segment" style="height:'+h+'%;background:'+color+'"><div class="tooltip">Offset: 0x'+d.offset.toString(16)+" | Entropy: "+d.entropy.toFixed(2)+"</div></div>";
}
html+="</div>";
container.innerHTML+=html;
}

function toggleSection(id){
var content=document.getElementById("content-"+id);
var toggle=document.getElementById("toggle-"+id);
content.classList.toggle("collapsed");
toggle.classList.toggle("collapsed");
}

function setupFilter(id){
var input=document.getElementById("filter-"+id);
if(!input)return;
input.addEventListener("input",function(){filterTable(id);});
}

function filterTable(id){
var input=document.getElementById("filter-"+id);
var table=document.getElementById("table-"+id);
if(!input||!table)return;
var term=input.value.toLowerCase();
var rows=table.querySelectorAll("tbody tr");
for(var i=0;i<rows.length;i++){
var text=rows[i].textContent.toLowerCase();
rows[i].style.display=text.indexOf(term)>=0?"":"none";
}
}

function formatSize(bytes){
if(bytes<1024)return bytes+" B";
if(bytes<1048576)return(bytes/1024).toFixed(1)+" KB";
if(bytes<1073741824)return(bytes/1048576).toFixed(1)+" MB";
return(bytes/1073741824).toFixed(2)+" GB";
}

function escHtml(s){
var d=document.createElement("div");
d.textContent=s;
return d.innerHTML;
}

document.addEventListener("DOMContentLoaded",init);
</script>
</body>
</html>`

	t, err := template.New("report").Parse(tmpl)
	if err != nil {
		return "", err
	}

	var sb strings.Builder
	err = t.Execute(&sb, map[string]interface{}{
		"Title":       report.Title,
		"Description": report.Description,
		"GeneratedAt": report.GeneratedAt,
		"ToolVersion": report.ToolVersion,
		"JSON":        template.JS(reportJSON),
	})
	if err != nil {
		return "", err
	}

	return sb.String(), nil
}
