package export

import (
	"fmt"
	"os"
	"strings"
	"time"
)

// PDFReport represents a PDF report structure
type PDFReport struct {
	Title       string
	Description string
	GeneratedAt string
	ToolVersion string
	Sections    []PDFSection
}

// PDFSection represents a section in the PDF report
type PDFSection struct {
	Title   string
	Content string
}

// GeneratePDFReport generates a PDF report from analysis results
func GeneratePDFReport(results *AnalysisResults, outputPath string) error {
	report := &PDFReport{
		Title:       "Filo Analysis Report",
		Description: "Forensic analysis report generated by filo-go",
		GeneratedAt: time.Now().Format(time.RFC3339),
		ToolVersion: "0.4.0",
		Sections:    []PDFSection{},
	}

	// Add file info section
	if results.FileInfo != nil {
		report.Sections = append(report.Sections, PDFSection{
			Title: "File Information",
			Content: fmt.Sprintf("Name: %s\nSize: %d bytes\nType: %s\nMIME: %s\nSHA256: %s\nEntropy: %.2f",
				results.FileInfo.Name,
				results.FileInfo.Size,
				results.FileInfo.Type,
				results.FileInfo.MIME,
				results.FileInfo.SHA256,
				results.FileInfo.Entropy),
		})
	}

	// Add signatures section
	if len(results.Signatures) > 0 {
		var sigList []string
		for _, sig := range results.Signatures {
			sigList = append(sigList, fmt.Sprintf("- %s - %s (offset: %d, confidence: %.1f%%)",
				sig.Name, sig.Description, sig.Offset, sig.Confidence*100))
		}
		report.Sections = append(report.Sections, PDFSection{
			Title:   "Detected Signatures",
			Content: strings.Join(sigList, "\n"),
		})
	}

	// Add strings section
	if len(results.Strings) > 0 {
		var stringList []string
		for i, s := range results.Strings {
			if i >= 50 { // Limit to 50 strings for PDF
				break
			}
			stringList = append(stringList, fmt.Sprintf("0x%X [%s] %s", s.Offset, s.Type, s.Value))
		}
		report.Sections = append(report.Sections, PDFSection{
			Title:   "Extracted Strings",
			Content: strings.Join(stringList, "\n"),
		})
	}

	// Add metadata section
	if len(results.Metadata) > 0 {
		var metaList []string
		for key, value := range results.Metadata {
			metaList = append(metaList, fmt.Sprintf("%s: %v", key, value))
		}
		report.Sections = append(report.Sections, PDFSection{
			Title:   "Metadata",
			Content: strings.Join(metaList, "\n"),
		})
	}

	// Add security section
	if len(results.SecurityIssues) > 0 {
		var securityList []string
		for _, issue := range results.SecurityIssues {
			securityList = append(securityList, fmt.Sprintf("[%s] %s: %s",
				issue.Severity, issue.Type, issue.Description))
		}
		report.Sections = append(report.Sections, PDFSection{
			Title:   "Security Issues",
			Content: strings.Join(securityList, "\n"),
		})
	}

	// Generate PDF
	pdfContent := generatePDF(report)

	// Write to file
	return os.WriteFile(outputPath, pdfContent, 0644)
}

// generatePDF generates a simple PDF file
func generatePDF(report *PDFReport) []byte {
	var sb strings.Builder

	// PDF header
	sb.WriteString("%PDF-1.4\n")
	sb.WriteString("%âãÏÓ\n")

	// Catalog
	sb.WriteString("1 0 obj\n")
	sb.WriteString("<< /Type /Catalog /Pages 2 0 R >>\n")
	sb.WriteString("endobj\n")

	// Pages
	sb.WriteString("2 0 obj\n")
	sb.WriteString("<< /Type /Pages /Kids [3 0 R] /Count 1 >>\n")
	sb.WriteString("endobj\n")

	// Page
	sb.WriteString("3 0 obj\n")
	sb.WriteString("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\n")
	sb.WriteString("endobj\n")

	// Content stream
	content := buildPDFContent(report)
	sb.WriteString("4 0 obj\n")
	sb.WriteString(fmt.Sprintf("<< /Length %d >>\n", len(content)))
	sb.WriteString("stream\n")
	sb.WriteString(content)
	sb.WriteString("\nendstream\n")
	sb.WriteString("endobj\n")

	// Font
	sb.WriteString("5 0 obj\n")
	sb.WriteString("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\n")
	sb.WriteString("endobj\n")

	// Cross-reference table
	xrefOffset := sb.Len()
	sb.WriteString("xref\n")
	sb.WriteString("0 6\n")
	sb.WriteString("0000000000 65535 f \n")
	sb.WriteString("0000000009 00000 n \n")
	sb.WriteString("0000000058 00000 n \n")
	sb.WriteString("0000000115 00000 n \n")
	sb.WriteString("0000000266 00000 n \n")
	sb.WriteString("0000000400 00000 n \n")

	// Trailer
	sb.WriteString("trailer\n")
	sb.WriteString("<< /Size 6 /Root 1 0 R >>\n")
	sb.WriteString("startxref\n")
	sb.WriteString(fmt.Sprintf("%d\n", xrefOffset))
	sb.WriteString("%%EOF\n")

	return []byte(sb.String())
}

// buildPDFContent builds the content stream for the PDF
func buildPDFContent(report *PDFReport) string {
	var sb strings.Builder

	// Title
	sb.WriteString("BT\n")
	sb.WriteString("/F1 24 Tf\n")
	sb.WriteString("36 750 Td\n")
	sb.WriteString(fmt.Sprintf("(%s) Tj\n", escapePDFString(report.Title)))
	sb.WriteString("ET\n")

	// Description
	sb.WriteString("BT\n")
	sb.WriteString("/F1 10 Tf\n")
	sb.WriteString("36 720 Td\n")
	sb.WriteString(fmt.Sprintf("(%s) Tj\n", escapePDFString(report.Description)))
	sb.WriteString("ET\n")

	// Generated at
	sb.WriteString("BT\n")
	sb.WriteString("/F1 10 Tf\n")
	sb.WriteString("36 700 Td\n")
	sb.WriteString(fmt.Sprintf("(Generated: %s) Tj\n", escapePDFString(report.GeneratedAt)))
	sb.WriteString("ET\n")

	// Sections
	y := 660.0
	for _, section := range report.Sections {
		if y < 100 {
			break // Stop if we're running out of space
		}

		// Section title
		sb.WriteString("BT\n")
		sb.WriteString("/F1 14 Tf\n")
		sb.WriteString(fmt.Sprintf("36 %.1f Td\n", y))
		sb.WriteString(fmt.Sprintf("(%s) Tj\n", escapePDFString(section.Title)))
		sb.WriteString("ET\n")
		y -= 20

		// Section content
		sb.WriteString("BT\n")
		sb.WriteString("/F1 10 Tf\n")
		sb.WriteString(fmt.Sprintf("36 %.1f Td\n", y))

		// Split content into lines
		lines := strings.Split(section.Content, "\n")
		for _, line := range lines {
			if y < 50 {
				break
			}
			sb.WriteString(fmt.Sprintf("(%s) Tj\n", escapePDFString(line)))
			sb.WriteString("0 -12 Td\n")
			y -= 12
		}
		sb.WriteString("ET\n")
		y -= 10
	}

	return sb.String()
}

// escapePDFString escapes special characters for PDF strings
func escapePDFString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "(", "\\(")
	s = strings.ReplaceAll(s, ")", "\\)")
	return s
}

// FormatPDFPath formats a path for PDF output
func FormatPDFPath(inputPath string) string {
	dir := "."
	name := "report"
	ext := ".pdf"

	if inputPath != "" {
		// Extract directory and filename from input path
		lastSlash := strings.LastIndex(inputPath, "/")
		if lastSlash >= 0 {
			dir = inputPath[:lastSlash]
			name = inputPath[lastSlash+1:]
		} else {
			name = inputPath
		}

		// Remove extension
		lastDot := strings.LastIndex(name, ".")
		if lastDot >= 0 {
			name = name[:lastDot]
		}
	}

	return fmt.Sprintf("%s/%s%s", dir, name, ext)
}
